apiVersion: v1
kind: Service
metadata:
  name: user-authentication-service
  labels:
    app: user-authentication-service
spec:
  selector:
    app: user-authentication-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP