apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-service/k8s/
  - product-catalog-service/k8s/
  - cart-service/k8s/
  - checkout-service/k8s/
  - payment-service/k8s/
  - user-authentication-service/k8s/
  - shipping-service/k8s/
  - ingress.yaml