apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-service/k8s/deployment.yaml
  - frontend-service/k8s/service.yaml
  - product-catalog-service/k8s/deployment.yaml
  - product-catalog-service/k8s/service.yaml
  - cart-service/k8s/deployment.yaml
  - cart-service/k8s/service.yaml
  - checkout-service/k8s/deployment.yaml
  - checkout-service/k8s/service.yaml
  - payment-service/k8s/deployment.yaml
  - payment-service/k8s/service.yaml
  - user-authentication-service/k8s/deployment.yaml
  - user-authentication-service/k8s/service.yaml
  - shipping-service/k8s/deployment.yaml
  - shipping-service/k8s/service.yaml
  - ingress.yaml