---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-secrets
  namespace: shopping
spec:
  encryptedData:
    jwt-secret: AgB424e+aEpDWW9ag+HMKYyXTTHjuQN32MSZ8CHGGZi93kkjh81E9jJ6G+x4/FOGoi8ySzBYtI4kVMtaztR2OGDYR+G42AF9eKUd/nqLX7ELwB0RY5WQENBGnIYn2vMsBxrxzT5bTVlNniuIxdYuYZpKso4LFNqSflCwQgmasg4DuNqOcoBK2tF+hbXJBxFUJUu+wnRZTyTfTF8BshuuPs3adxraJzdYnNyh9pGpm48g8paLl1VpGxbf6iONkVWbINMlcZPER2O1Aqx3KH0EiJ+cXlNoNh7PHE1LjQCJsR3JBdobKVvUJaVFD8tLysoFSIS0lV0n7+WkWVsmEOAJNaVB3rJTV85TbalD2dCmNY4ohk0pif4pvwpd7onSZp5zgHLLMacdviw/1tIagDY60+HHq9JO0xWlsEtEgf7+ikBmIgO2s/aY1biqYoAkv9d8zDQ60ItJJ2gcosaCIW1ljZuKvd9/kmJQDATSFSMZuYaqriNolrJWxN+pyZq9nkd5bdlIIR2nI3BQS80vkky5dvlU3GVIRt9ioQGyprkRgp3jnFDggJCM6zQKtKJCsxbxGo5lPW5FSOqHsx6RwnHQjQxFFCofGJJxXfvJdc57fGvgp6q70Dwlc5ASn3oLIHzQ0o+ouEAjMDYAXgb+MOq22sVrq04LFoTtp73blLzS67LhT5CqZ2iEJdAcBlk/5V3PlnrrxFxKZfL+YcAgAJdkjXL5uyXXD2kdujJTfcKmHDnHOvvzRLX9/noOB5A=
  template:
    metadata:
      creationTimestamp: null
      name: auth-secrets
      namespace: shopping
