# Checkout Service — values for the mono-chart
serviceName: checkout-service
environment: dev

image:
  repository: ""
  name: checkout-service
  tag: latest
  pullPolicy: Never

replicas: 2
containerPort: 5001
servicePort: 5001

serviceAccountName: checkout-sa

health:
  enabled: true
  path: /health

env:
  - name: PORT
    value: "5001"
  - name: CART_SERVICE_URL
    value: "http://cart-service:3002"
  - name: PAYMENT_SERVICE_URL
    value: "http://payment-service:5002"
  - name: SHIPPING_SERVICE_URL
    value: "http://shipping-service:8080"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60

pdb:
  enabled: true
  minAvailable: 1
